import { ClerkProvider } from '@clerk/nextjs'

import TopNav from './_components/topnav'

import '@/styles/globals.css'

export const metadata = {
  manifest: '/manifest.json',
  title: 't3 gallery',
  description: 'Generated by create-t3-app',
  icons: {
    icon: '/favicon.png',
    shortcut: '/favicon.png',
    apple: '/icon.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body>
          <div className='flex min-h-screen flex-col gap-4 bg-cb-dark-blue text-cb-white'>
            <TopNav />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
