import '@/styles/globals.css'

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const TopNav = () => (
  <nav className='border-cb-dusty-blue flex w-full items-center justify-between border-b p-4'>
    <div className='text-3xl font-extrabold leading-9 tracking-tight sm:text-4xl sm:leading-10'>
      gallery
    </div>
    <div className='text-xl font-semibold'>sign in</div>
  </nav>
)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div className='bg-cb-dark-blue text-cb-white flex min-h-screen flex-col gap-4'>
          <TopNav />
          {children}
        </div>
      </body>
    </html>
  )
}
